name: KPManager
api-version: 1.19
version: 1.4
main: in.rs.milivojevic.KPManager.Main
author: Kamey_
license: MIT
description: This plugin displays a welcome message to players when they join the server, including their name.