name: KPManager
api-version: 1.19
version: v1.8
main: in.rs.milivojevic.KPManager.Main
author: Kamey_
license: GPLv3
description: Welcome players with personalized messages, show country of origin, manage tab list and monitor ping.
permissions:
  KPManager.update:
    description: Allows player to see update notifications
    default: op