name: Build and Test Java Code
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          java-package: jdk
          architecture: x64
          check-latest: false
          distribution: 'corretto'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true

      - name: Build with Maven
        run: mvn clean install

      - name: Test with JUnit
        run: mvn test

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.5
          release_name: KManager 1.5
          draft: true
          prerelease: true
